name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    name: ${{ matrix.os }}-${{ matrix.node }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 18.x
          - 20.x
          - 21.x
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"