name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://unreachable-url.com'
          - 'invalid-cfkjsagjajoa'
        default: https://www.google.com
      max_trials:
        description: "Maximum trials until actions fails"
        type: string
        default: '10'
        required: false
      delay:
        description: "delay in seconds between trials"
        type: string
        default: '5'
        required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}